<?php

/**
 * This is the model base class for the table "actividad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Actividad".
 *
 * Columns in table "actividad" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $entidad_tipo
 * @property integer $entidad_id
 * @property string $tipo
 * @property integer $usuario_id
 * @property string $fecha
 * @property string $detalle
 *
 */
abstract class BaseActividad extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'actividad';
    }

    public static function representingColumn() {
        return 'entidad_tipo';
    }

    public function rules() {
        return array(
            array('entidad_tipo, entidad_id, tipo, usuario_id, fecha', 'required'),
            array('entidad_id, usuario_id', 'numerical', 'integerOnly'=>true),
            array('entidad_tipo', 'length', 'max'=>64),
            array('tipo', 'length', 'max'=>7),
            array('detalle', 'safe'),
            array('tipo', 'in', 'range' => array('CREATE','UPDATE','DELETE','RESTORE')), // enum,
            array('detalle', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, entidad_tipo, entidad_id, tipo, usuario_id, fecha, detalle', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'entidad_tipo' => Yii::t('app', 'Entidad Tipo'),
                'entidad_id' => Yii::t('app', 'Entidad'),
                'tipo' => Yii::t('app', 'Tipo'),
                'usuario_id' => Yii::t('app', 'Usuario'),
                'fecha' => Yii::t('app', 'Fecha'),
                'detalle' => Yii::t('app', 'Detalle'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('entidad_tipo', $this->entidad_tipo, true);
        $criteria->compare('entidad_id', $this->entidad_id);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('usuario_id', $this->usuario_id);
        $criteria->compare('fecha', $this->fecha, true);
        $criteria->compare('detalle', $this->detalle, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}