<?php

/**
 * This is the model base class for the table "tx_trasaccion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TxTrasaccion".
 *
 * Columns in table "tx_trasaccion" available as properties of the model,
 * followed by relations of table "tx_trasaccion" available as properties of the model.
 *
 * @property integer $id
 * @property double $monto_cuota
 * @property string $tipo
 * @property string $observaciones
 * @property integer $usuario_creacion_id
 * @property string $fecha_creacion
 * @property integer $usuario_actualizacion_id
 * @property string $fecha_actualizacion
 * @property integer $clt_deuda_id
 * @property integer $tx_descripcion_palntilla_id
 *
 * @property CltDeuda $cltDeuda
 * @property TxDescripcionPalntilla $txDescripcionPalntilla
 */
abstract class BaseTxTrasaccion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tx_trasaccion';
    }

    public static function representingColumn() {
        return 'fecha_creacion';
    }

    public function rules() {
        return array(
            array('monto_cuota, usuario_creacion_id, clt_deuda_id', 'required'),
            array('usuario_creacion_id, usuario_actualizacion_id, clt_deuda_id, tx_descripcion_palntilla_id', 'numerical', 'integerOnly'=>true),
            array('monto_cuota', 'numerical'),
            array('tipo', 'length', 'max'=>7),
            array('observaciones, fecha_actualizacion', 'safe'),
            array('tipo', 'in', 'range' => array('ADEUDAR','PAGAR')), // enum,
            array('tipo, observaciones, usuario_actualizacion_id, fecha_actualizacion, tx_descripcion_palntilla_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, monto_cuota, tipo, observaciones, usuario_creacion_id, fecha_creacion, usuario_actualizacion_id, fecha_actualizacion, clt_deuda_id, tx_descripcion_palntilla_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cltDeuda' => array(self::BELONGS_TO, 'CltDeuda', 'clt_deuda_id'),
            'txDescripcionPalntilla' => array(self::BELONGS_TO, 'TxDescripcionPalntilla', 'tx_descripcion_palntilla_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'monto_cuota' => Yii::t('app', 'Monto Cuota'),
                'tipo' => Yii::t('app', 'Tipo'),
                'observaciones' => Yii::t('app', 'Observaciones'),
                'usuario_creacion_id' => Yii::t('app', 'Usuario Creacion'),
                'fecha_creacion' => Yii::t('app', 'Fecha Creacion'),
                'usuario_actualizacion_id' => Yii::t('app', 'Usuario Actualizacion'),
                'fecha_actualizacion' => Yii::t('app', 'Fecha Actualizacion'),
                'clt_deuda_id' => Yii::t('app', 'Clt Deuda'),
                'tx_descripcion_palntilla_id' => Yii::t('app', 'Tx Descripcion Palntilla'),
                'cltDeuda' => null,
                'txDescripcionPalntilla' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('monto_cuota', $this->monto_cuota);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('observaciones', $this->observaciones, true);
        $criteria->compare('usuario_creacion_id', $this->usuario_creacion_id);
        $criteria->compare('fecha_creacion', $this->fecha_creacion, true);
        $criteria->compare('usuario_actualizacion_id', $this->usuario_actualizacion_id);
        $criteria->compare('fecha_actualizacion', $this->fecha_actualizacion, true);
        $criteria->compare('clt_deuda_id', $this->clt_deuda_id);
        $criteria->compare('tx_descripcion_palntilla_id', $this->tx_descripcion_palntilla_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'CTimestampBehavior' => array(
                'class' => 'zii.behaviors.CTimestampBehavior',
                'createAttribute' => 'fecha_creacion',
                'updateAttribute' => 'fecha_actualizacion',
                'timestampExpression' => new CDbExpression('NOW()'),
            )
        ), parent::behaviors());
    }
}