<?php

/**
 * This is the model base class for the table "movil_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MovilUser".
 *
 * Columns in table "movil_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id_dispositivo
 * @property integer $id_user
 * @property string $estado
 *
 */
abstract class BaseMovilUser extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'movil_user';
    }

    public static function representingColumn() {
        return 'estado';
    }

    public function rules() {
        return array(
            array('id_dispositivo', 'required'),
            array('id_user', 'numerical', 'integerOnly'=>true),
            array('id_dispositivo', 'length', 'max'=>45),
            array('estado', 'length', 'max'=>3),
            array('estado', 'in', 'range' => array('IN','OUT')), // enum,
            array('id_user, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_dispositivo, id_user, estado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_dispositivo' => Yii::t('app', 'Id Dispositivo'),
                'id_user' => Yii::t('app', 'Id User'),
                'estado' => Yii::t('app', 'Estado'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_dispositivo', $this->id_dispositivo, true);
        $criteria->compare('id_user', $this->id_user);
        $criteria->compare('estado', $this->estado, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}